#include "Math/Matrix4x4.h"

namespace ETL
{
	namespace Math
	{
#define ETL_INTERNAL_EXPLICIT_INST_DEF(T, layout) template struct Matrix4x4<T, layout>

		ETL_INTERNAL_EXPLICIT_INST_DEF(float, ETL_MATRIX_LAYOUT_COLUMN_MAJOR);
		ETL_INTERNAL_EXPLICIT_INST_DEF(double, ETL_MATRIX_LAYOUT_COLUMN_MAJOR);
		ETL_INTERNAL_EXPLICIT_INST_DEF(float, ETL_MATRIX_LAYOUT_ROW_MAJOR);
		ETL_INTERNAL_EXPLICIT_INST_DEF(double, ETL_MATRIX_LAYOUT_ROW_MAJOR);

#undef ETL_INTERNAL_EXPLICIT_INST_DEF
	}
}